#define MY_0            19
#define MY_1            10
#define MY_2            11
#define MY_3            12
#define MY_4            13
#define MY_5            14
#define MY_6            15
#define MY_7            16
#define MY_8            17
#define MY_9            18
#define MY_BackSpace    22
#define MY_Delete       119
#define MY_Down         116
#define MY_End          115
#define MY_F5           71
#define MY_Home         110
#define MY_Left         113
#define MY_Page_Down    117
#define MY_Page_Up      112
#define MY_Return       36
#define MY_Right        114
#define MY_Tab          23
#define MY_Up           111
#define MY_bracketleft  34
#define MY_bracketright 35
#define MY_grave        49
#define MY_space        65
#define MY_b            56
#define MY_c            54
#define MY_d            40
#define MY_f            41
#define MY_i            31
#define MY_m            58
#define MY_o            32
#define MY_p            33
#define MY_q            24
#define MY_t            28
#define MY_u            30
#define MY_y            29
